### PR TITLE
Allow additional properties

### PR DESCRIPTION
**Pull request by slyboots**
Alacritty supports additional properties and yaml anchors in it's config file. This is useful for messing around with themes. [relevant issue](https://github.com/alacritty/alacritty/issues/2710)

I noticed nvim throwing an error on my custom themes definition while editing my alacritty config and was a little confused until I remembered I was using schemastore for validation and found this.

### CODE REVIEW

**Review by KillDozerX2 — APPROVED** [review]

**Comment by KillDozerX2** [comment]
This is good, thanks. I could also use some help moving away from vscode though.

**Comment by slyboots** [comment]
I switched from VSCode to neovim awhile back. If you'd like a tip on trying out nvim, I'd recommend immediately installing the coc.nvim plugin.


Other vim users would probably disagree with me but coc.nvim is probably one of the easiest "batteries semi-included" language server plugins to start with and the configuration is very similar to vscode. It also has a ton of community support and documentation. So you can get in to vim without having to lose your autocomplete and smart navigation.

**Comment by slyboots** [comment]
Then after you get more comfortable with nvim you can switch over to using it's built in LSP support instead of a plugin

**Comment by slyboots** [comment]
also thank you for the merge!

**Pull request merged**
